### ISSUE TITLE
Spotify Ads Toasts never disappear

### ISSUE THREAD

**Issue by AlphaGit** [nachmore/toastify#12]
Hi! First of all -- thank you for this wonderful product.

It seems that while Spotify is playing ads, Toastify will show a toast notification (correctly), but the toast doesn't go away in the configured time. Rather, it stays for the whole duration of the ad.

**Comment by gahujipo** [comment]
In my case it behaves as followed: When Spotify is playing normal music the notification disappears as expected, but when Spotify is playing a podcast the notification does not disappear. I am using the [Spotify Music app from the Microsoft Store.](https://www.microsoft.com/en-us/store/p/spotify-music/9ncbcszsjrsb)

**Comment by nachmore** [comment]
Ad toast removed as Spotify removed the clear indication that an ad was playing.
