### ISSUE TITLE
Album cover art not showing

### ISSUE THREAD

**Issue by Jabbl** [nachmore/toastify#15]
Seems that no matter what I do, the toast only shows the toastify icon where the album art is supposed to be. 
Currently using v.1.8.3

**Comment by aleab** [comment]
@Jabbl, this project seems dead. There have been some changes in Spotify itself that made Toastify non-functional since quite some time.
I've forked this project [here](/aleab/toastify), if you are interested.

**Comment by nachmore** [comment]
Fixed in latest.

**Comment by thecappadonna** [comment]
Everything works for me except for the progress bar which I don't mind...It does showing online songs covers...But doesn't show my local music covers...Is there any way to fix that problem? How to make it look for a cover when I have added covers to all local songs and the covers appear everywhere...But not in Toastify...Can you help me?
