### ISSUE TITLE
Bug Introduced in 1.7.6+: Toast alert box steals text cursor focus 

### ISSUE THREAD

**Issue by ashtonian** [nachmore/toastify#2]
Re-posting the codeplex issue here as this might get a better response/ be the newer home?

https://toastify.codeplex.com/workitem/13681  

"Toastify shows version 1.7.6 (though I have downloaded and installed 1.7.7)

If Toast shows while typing in another program (reproduced in Visual Studio, Google Chrome (44.0.2403.155 m), Notepad++, and Google Hangouts), it steals the focus, causing an interruption to typing.

I usually leave Toast open while programming to see what song pops on, but I will have to disable Toast until this is resolved."

**Comment by junkiebev** [comment]
I have both issues as well.

**Comment by nachmore** [comment]
Thanks, weirdly the focus stealing doesn't repro on my test / music machine but does repro everywhere else. I have a fix which I'll be pushing out shortly (for the update version as well).
