### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by otaviolarrosa** [nachmore/toastify#7]
otavio@DESKTOP-OSK0AN7 MINGW64 /c/GitHub/toastify (otaviolarrosa)
$ git push origin otaviolarrosa
remote: Permission to nachmore/toastify.git denied to otaviolarrosa.
fatal: unable to access 'https://github.com/nachmore/toastify.git/': The requested URL returned error: 403

Why I can't push my branch, to open a pullrequest ?

**Comment by tplk** [comment]
Because you're supposed to push to your fork to create a pull request.

**Comment by tplk** [comment]
After you push to your fork go to the github and click this button. Then select wanted branch (you might need to click "compare across forks" under title) and create a pull request.
![image](https://cloud.githubusercontent.com/assets/20531968/21907886/88537372-d922-11e6-95de-a7b43f332754.png)
