### ISSUE TITLE
Support the Windows Store Spotify app

### ISSUE THREAD

**Issue by marczellm** [nachmore/toastify#9]
Today Spotify Desktop arrived on the Windows Store.
Toastify does not find the app and displays an error: "Could not find Spotify path in registry"
It would be great if Toastify worked with the Store version too.

**Comment by aleab** [comment]
Hi marczellm.
I have recently forked this project at [aleab/toastify](https://github.com/aleab/toastify).
Today, after seeing this issue, I managed to make Toastify compatible with the Windows Store version of Spotify. If you wanna give my version a try, you can find the latest release [here](https://github.com/aleab/toastify/releases).

**Comment by gahujipo** [comment]
@aleab Wow, your fork is really great. I like that.
